Repository bmc-toolbox/bmclib, pull requests merged in 2023-09, with the labels that each got.

#343 RPC provider
  README.md
  client.go
  client_test.go
  examples/rpc/main.go
  go.mod
  go.sum
  lint.mk
  logging/logging.go
  option.go
  providers/rpc/doc.go
  providers/rpc/experimental.go
  providers/rpc/http.go
  providers/rpc/http_test.go
  providers/rpc/logging.go
  providers/rpc/payload.go
  providers/rpc/rpc.go
  providers/rpc/rpc_test.go
  providers/rpc/signature.go
Labels: feature, ready-to-merge, bmclib v2

#348 Fix copying of request body:
  examples/rpc/main.go
  providers/rpc/http_test.go
  providers/rpc/logging.go
  providers/rpc/payload.go
  providers/rpc/rpc.go
  providers/rpc/rpc_test.go
Labels: bug, ready-to-merge

#350 Remove returning the response body:
  providers/rpc/http.go
  providers/rpc/rpc_test.go
Labels: ready-to-merge

#353 Redfish disable Etag match header
  go.mod
  go.sum
  internal/redfishwrapper/client.go
  internal/redfishwrapper/client_test.go
  internal/redfishwrapper/power.go
  providers/redfish/redfish.go
Labels: ready-to-merge

#349 Add SEL Clear Support
  .devcontainer/devcontainer.json
  bmc/sel.go
  bmc/sel_test.go
  client.go
  examples/sel/main.go
  internal/ipmi/ipmi.go
  internal/redfishwrapper/sel.go
  providers/ipmitool/ipmitool.go
  providers/ipmitool/ipmitool_test.go
  providers/providers.go
  providers/redfish/redfish.go
  providers/redfish/sel.go
Labels: ready-to-merge

#351 Supermicro x11 supported models
  providers/supermicro/firmware.go
Labels: ready-to-merge

#354 Client opts fixes
  client.go
  option.go
  providers/redfish/redfish.go
Labels: ready-to-merge
